<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SVijay" failures="3" tests="7" name="Test" time="75.685" errors="0" timestamp="2024-09-12T13:37:32 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verify_account_Registration" time="2.456"/>
  <testcase classname="testCases.TC002_Login_Test" name="veryfy_login" time="21.832">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC002_Login_Test.veryfy_login(TC002_Login_Test.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- veryfy_login -->
  <testcase classname="testCases.TC003_Login_DDT" name="veryfy_login" time="3.822"/>
  <testcase classname="testCases.TC003_Login_DDT" name="veryfy_login" time="4.305">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_Login_DDT.veryfy_login(TC003_Login_DDT.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- veryfy_login -->
  <testcase classname="testCases.TC003_Login_DDT" name="veryfy_login" time="2.69">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_Login_DDT.veryfy_login(TC003_Login_DDT.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- veryfy_login -->
  <testcase classname="testCases.TC003_Login_DDT" name="veryfy_login" time="11.604"/>
  <testcase classname="testCases.TC003_Login_DDT" name="veryfy_login" time="4.608"/>
</testsuite> <!-- Test -->
